# Generated by Django 5.2 on 2025-06-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_sale_options_alter_salesmetrics_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
    ]
