# Generated by Django 5.1.7 on 2025-05-05 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_sale_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.credit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
