# Generated by Django 5.1.7 on 2025-05-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_credititem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesmetrics',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Sales Metrics'},
        ),
        migrations.RemoveField(
            model_name='credit',
            name='product',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='quantity',
        ),
    ]
