# Generated by Django 5.1.7 on 2025-05-05 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_credit_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date_sold']},
        ),
        migrations.AddField(
            model_name='sale',
            name='credit_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='inventory.credit'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_credit_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
